from Socket_Encryptor import GetSocketEncryptor

encryptor = GetSocketEncryptor()
print(encryptor.encrypt(b'plaintesplaintesplaintesplaintesplaintesplaintesplaintesplaintesplaintesplaintesplaintesplaintes'))